import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { generateRayId, validateRayId } from './rayId.js';

/**
 * **Feature: cloudflare-error-page-generator, Property 3: Ray ID Format Validity**
 * 
 * *For any* Ray ID generated by the RayIdGenerator, the output SHALL be exactly 
 * 16 characters long and contain only valid hexadecimal characters (0-9, a-f).
 * 
 * **Validates: Requirements 3.1, 3.3**
 */
describe('Ray ID Generator - Property Tests', () => {
  it('Property 3: Generated Ray IDs are always 16 hex characters', () => {
    fc.assert(
      fc.property(fc.constant(null), () => {
        const rayId = generateRayId();
        
        // Must be exactly 16 characters
        expect(rayId).toHaveLength(16);
        
        // Must contain only valid hex characters (0-9, a-f)
        expect(rayId).toMatch(/^[0-9a-f]{16}$/);
        
        // Must pass our own validation
        expect(validateRayId(rayId)).toBe(true);
      }),
      { numRuns: 100 }
    );
  });
});

// Unit tests for Ray ID generator
describe('Ray ID Generator - Unit Tests', () => {
  it('generates a Ray ID with length 16', () => {
    const rayId = generateRayId();
    expect(rayId).toHaveLength(16);
  });

  it('generates a Ray ID containing only hex characters', () => {
    const rayId = generateRayId();
    expect(rayId).toMatch(/^[0-9a-f]+$/);
  });

  it('validates valid Ray IDs', () => {
    expect(validateRayId('0123456789abcdef')).toBe(true);
    expect(validateRayId('ABCDEF0123456789')).toBe(true);
    expect(validateRayId('a1b2c3d4e5f67890')).toBe(true);
  });

  it('rejects invalid Ray IDs', () => {
    // Too short
    expect(validateRayId('abc123')).toBe(false);
    // Too long
    expect(validateRayId('0123456789abcdef0')).toBe(false);
    // Invalid characters
    expect(validateRayId('ghijklmnopqrstuv')).toBe(false);
    // Empty string
    expect(validateRayId('')).toBe(false);
    // Non-string
    expect(validateRayId(null)).toBe(false);
    expect(validateRayId(undefined)).toBe(false);
    expect(validateRayId(123456789012345)).toBe(false);
  });
});
